"""Initial migration

Revision ID: 22a852aa4fb1
Revises: 
Create Date: 2025-07-25 21:19:02.973315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a852aa4fb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sura',
    sa.Column('num_sura', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('num_sura')
    )
    op.create_table('ayat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sura', sa.Integer(), nullable=False),
    sa.Column('num_aya', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['sura'], ['sura.num_sura'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ayat')
    op.drop_table('sura')
    # ### end Alembic commands ###
